### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by BarenoFulafun** [Tsukihimates/Tsukihime-Translation#1035]
Hello! At first, I would thank you for translation! Hope you'll keep working!
Now the issue, I installed my pretty font and since it's monospaced it dispays fine. Of course, font can be increased in the Word and other programs. But defolt size in Tsukihime is kinda small. I mean, really small. There's any ways to increase size? Because font is actually cool and fits with style of Tsukihime, but the size leaves much to be desired. Thank you!

**Comment by rschlaikjer** [comment]
The game does not have a way to modify the font size. We do not support using fonts other than the inbuilt font, as it has a number of extensions to support our extended text effects.
