### ISSUE TITLE
Script folder name change causing issue with updating game script

### ISSUE THREAD

**Issue by RagingBuracku** [Tsukihimates/Tsukihime-Translation#263]
So I was attempting to update my game script as I usually do, but I noticed with the latest update on here, the script folder is now differently named/organized than it was before. As a result, when I usually just drag the "1_0_2current_en_script" into the deepLuna update folder and press open translation, the game script would not update and instead opens the main translation box. I checked the log within VScode (I use that to run the script because cmd and powershell don't like to cooperate with me) and it tells me the same thing being "Bad number of pages in "game script file"". So I'm not entirely sure on what I should do to be able to update everything like I would before. 

I'll also post SC's to help explain my point further in case my wording was confusing
![Screenshot 2022-01-09 135557](https://user-images.githubusercontent.com/59775668/148696535-77f0e6ac-67d5-4b38-aee2-9729fa575d5b.png)
![Screenshot 2022-01-09 135645](https://user-images.githubusercontent.com/59775668/148696568-03b72c85-6334-4c30-8e92-308dfb263ae0.png)
![Screenshot 2022-01-09 135741](https://user-images.githubusercontent.com/59775668/148696602-e923ae5e-25fe-4387-a4a1-df0b339236f4.png)

**Comment by AtaIanta** [comment]
Rename ```update``` folder to ```import``` if you are using newest files and download newest deepluna. Recently there were changes in deepluna and exported files have new format.

**Comment by rschlaikjer** [comment]
Hey there, yes, this is an expected issue. We recently updated the script format used by deepLuna to be a bit more expressive in order make it easier for our translators / TL checkers to do their work. In order to load the new-format scripts, you will also need to make sure you update to the latest version of deepLuna (currently v4.6).
As part of updating to the new deepLuna, you will need to re-extract the database. You can do this by makign sure that allscr.mrg and script_text.mrg (the raw 1.0.2 versions of the files) are in the directory, then launching the updated version of deepLuna and hitting 'Extract Text'. Once you've done that, copy the new-style script files into `import/` (not `update/`, since that's where it will search for 'old' format files), and then either close and reopen deepLuna or hit the new "Re-import updates" button on the translation window.

**Comment by RagingBuracku** [comment]
so where can I go to get the latest deeeLuna, cause on their github it just goes up to 3.11?

**Comment by AtaIanta** [comment]
Do not use versioned releases at the right, always download latest code.

![image](https://user-images.githubusercontent.com/42716753/148696970-6e0d68e2-1050-48ea-a32c-5575364a666c.png)

**Comment by rschlaikjer** [comment]
As Atalanta says, the best way to be up to date is download the current master version of the repo.
I have also just published the current tag as a release as well though.
https://github.com/Hakanaou/deepLuna/releases/tag/v4.6

**Comment by RagingBuracku** [comment]
yeah, so I downloaded the latest deepLuna Repo, but now when I run open translation I get this
![Screenshot 2022-01-09 141611](https://user-images.githubusercontent.com/59775668/148697217-c6fa5f2a-50ea-497f-afc7-9da7c496abc2.png)

**Comment by rschlaikjer** [comment]
Yes, as I mentioned above, you need to re-extract the DB
> As part of updating to the new deepLuna, you will need to re-extract the database. You can do this by making sure that allscr.mrg and script_text.mrg (the raw 1.0.2 versions of the files) are in the directory, then launching the updated version of deepLuna and hitting 'Extract Text'.

**Comment by RagingBuracku** [comment]
> Yes, as I mentioned above, you need to re-extract the DB
> 
> > As part of updating to the new deepLuna, you will need to re-extract the database. You can do this by making sure that allscr.mrg and script_text.mrg (the raw 1.0.2 versions of the files) are in the directory, then launching the updated version of deepLuna and hitting 'Extract Text'.

yeah you were right it worked, but just to make sure I don't f it up, what should I press to make sure I get an updated script file, cause it seems it has accepted the latest script but it still says "translated text 0%"

**Comment by rschlaikjer** [comment]
Oh, yeah I think there's a bug where that global translation % doesn't update when you import. If you click around into the scenes they should still be translated, and if you close/open it should update

**Comment by RagingBuracku** [comment]
> Oh, yeah I think there's a bug where that global translation % doesn't update when you import. If you click around into the scenes they should still be translated, and if you close/open it should update

yep it all seems to be working now, thanks for the help
