### ISSUE TITLE
Error when extracting text

### ISSUE THREAD

**Issue by CChandraa** [Tsukihimates/Tsukihime-Translation#565]
I tried to import the script files into DeepLuna, but when I try to extract text and overwrite the database this error shows up
![image](https://user-images.githubusercontent.com/103993665/164013653-2bf3af76-6881-423d-819e-3cc1dfa28faa.png)

**Comment by rschlaikjer** [comment]
Looks like you may be using the 1.0.0 version of the game MRGs. The script is slightly different in the 1.0.2 release, which is what we are targeting.

**Comment by CChandraa** [comment]
That's odd, could've sworn I updated it to 1.0.2. I will check then, thanks in advance.

**Comment by rschlaikjer** [comment]
Yes, modified mrgs go in the romfs folder. Note that you can't just copy it into the folder in this repo, you need to first copy the important bits from there to the load folder of whatever emulator you are using.

**Comment by CChandraa** [comment]
Yeah I got it, thanks!
