### ISSUE TITLE
Incorrect italics syntax on Ciel Day 5

### ISSUE THREAD

**Issue by ImportTaste** [Tsukihimates/Tsukihime-Translation#745]
https://github.com/Tsukihimates/Tsukihime-Translation/blob/c15429c58142d2cc10bfd82752b5fd75606985f1/script/Ciel/Day%205/05_01_CIEL05_1DASH.txt#L291

Should be `%{/i}` and not just `{/i}`

**Comment by Volvo-hackangel** [comment]
Fixed in https://github.com/Tsukihimates/Tsukihime-Translation/pull/747.
