### ISSUE TITLE
Crash to title screen during Day 6 Arach visit

### ISSUE THREAD

**Issue by ImportTaste** [Tsukihimates/Tsukihime-Translation#746]
When given a choice during the event 'Have Prof. Arach take care of me' on the 6th day, you're able to select something along the lines of 'once in a millennium'. This choice sends me back to the title screen.

**Comment by rschlaikjer** [comment]
Thanks for the report. We believe that this should actually be fixed already - please test again with the official patch once it's released and let us know if you still see issues.

**Comment by rschlaikjer** [comment]
The official patch is released, considering this issue closed.
