### ISSUE TITLE
During day 7 option "...What are the Twenty-Seven Ancestors?" is not selectable

### ISSUE THREAD

**Issue by Timinterrante** [Tsukihimates/Tsukihime-Translation#837]
![Day7 Choice Not selectable](https://user-images.githubusercontent.com/58995211/179372427-6c1b8bda-dc84-49ce-8d55-68d135699da1.png)
At this choice in the Arcueid route only options 1 and 3 are target-able, the game will not let you select option 2. This is on yuzu emulator running the most recent patch.

**Comment by rschlaikjer** [comment]
This is part of the game. You cannot pick option 2 without first clearing Arcueid route.
