### ISSUE TITLE
Incorrect translation (line repeated form further up) on Line 303 of 01_00_ARC01_1.txt

### ISSUE THREAD

**Issue by AlexMaskill** [Tsukihimates/Tsukihime-Translation#882]
Hey, I'm a Japanese learner doing my own translation of Tsukihime for practice and using your translation to check against, and I've noticed that on line 303 of 01_00_ARC01_1.txt, the translation of the line further up - line 333 - is there in place of what the actual japanese text says, 

人工の明かりに慣れきった眼に、覚めるような陽が差しこんだ。

which is something closer to
"The sun hit my eyes, acclimatised to the artificial light, like I was being awoken from sleep."

I assume your more experienced translators have their own translation there that just didn't get copied in, but thought I'd make you aware of the issue.

**Comment by rschlaikjer** [comment]
Good catch! Looks like this got introduced in an editing pass a couple weeks ago. Thanks for bringing it to our attention.
