### ISSUE TITLE
Save/Load menu causes a crash on Hardware.

### ISSUE THREAD

**Issue by brandon-dodds** [Tsukihimates/Tsukihime-Translation#924]
The patch is installed on the latest version, and the game is updated to version 1.02. All save files are maxed out. The most recent save that caused this bug was in Chapter 8, Eyes of Death Perception 2. I'm unsure what exact point the save caused an issue. But I'm sure it was after Mario arrived.

The Q.Save and Q.Load features still work.

**Comment by rschlaikjer** [comment]
Thanks for the report. Are you able to share your save file with us for investigation? I think we've seen one other instance where a save on a page with significant amounts of text on it triggers a bug.

**Comment by brandon-dodds** [comment]
[0x01001DC01486A000 0x01001DC01486A000.zip](https://github.com/Tsukihimates/Tsukihime-Translation/files/9389434/0x01001DC01486A000.0x01001DC01486A000.zip)

No worries, here is the zip containing my checkpoint dump. It seems like I saved directly on the screen where Shiki is reading about Modern Society. If you need any more information I would be more than happy to provide.
