### ISSUE TITLE
Distributing the patch for layeredFS

### ISSUE THREAD

**Issue by Raytwo** [Tsukihimates/Tsukihime-Translation#965]
Greetings,

As a fellow Switch modder, I couldn't help but notice that you seem to only distribute your patch as a NSP, which, on top of being rare, can lead to bans on hardware and is not recommended by SciresM (Atmosphere lead dev),

After some manipulations, I compared what files you guys have edited to the base game and used them through layeredFS on Switch, and it worked flawlessly for a full run of Arcueid's route (massive props to the translation team btw, amazing work and no typo).

Why did I bother to do this? Well, as I said, NSPs are unsafe on Switch and I think you guys would benefit a lot from distributing the patch for use with LayeredFS for the safety of your users (on top of not giving them a heart attack when reading the instructions).

I'm aware the installation guide mentions you will not take responsibility for bans, and that's totally fair, but you wouldn't need to warn people if you distributed a safe alternative. And hey, you can still keep the NSP way for ease of use on emulators!

I also noticed you distribute a patched exefs, why not use one of the existing alternatives like [Skyline](https://github.com/skyline-dev/skyline) (compatible with Ryujinx and soon with Yuzu) or [Starlight](https://github.com/shadowninja108/Starlight) (generates a IPS patch with an extra subsdk file that contains the code)? I have no intention to call you out on that, but I'm not sure distributing an edited copyrighted executable is a good idea if you want to protect yourselves from takedown notices.

**Comment by ruje0504** [comment]
I am a patch maker in other languages. I tried to seal the pictures that need to be modified in allpac into allpaccg. There will be problems with some of the teaching pictures of princess. Other pictures are normal, I don't know how to correctly patch exefs.

**Comment by ruje0504** [comment]
I'm a Chinese patch maker

**Comment by ruje0504** [comment]
Exefs are currently patched through IPS, but the patching is incomplete

**Comment by ruje0504** [comment]
I found that the error reporting problem only occurs in the switch. Ryujinx didn't appear, everything was normal

**Comment by ruje0504** [comment]
I recently found that this engine can be use the modified files in  allpac&allpaccg, and RULE files in allpac,  rename them and package them in allpacml.
Then the ips patch the exefs.
It does not need skyline and third-party SDKs to avoid being banned perfectly.
I'm from the Chinese localization team.

Thanks to rschlaikjer's mangetsu tool.
Thank you. Good luck with your work.

**Comment by Oliviert45** [comment]
> Greetings,
> 
> As a fellow Switch modder, I couldn't help but notice that you seem to only distribute your patch as a NSP, which, on top of being rare, can lead to bans on hardware and is not recommended by SciresM (Atmosphere lead dev),
> 
> After some manipulations, I compared what files you guys have edited to the base game and used them through layeredFS on Switch, and it worked flawlessly for a full run of Arcueid's route (massive props to the translation team btw, amazing work and no typo).
> 
> Why did I bother to do this? Well, as I said, NSPs are unsafe on Switch and I think you guys would benefit a lot from distributing the patch for use with LayeredFS for the safety of your users (on top of not giving them a heart attack when reading the instructions).
> 
> I'm aware the installation guide mentions you will not take responsibility for bans, and that's totally fair, but you wouldn't need to warn people if you distributed a safe alternative. And hey, you can still keep the NSP way for ease of use on emulators!
> 
> I also noticed you distribute a patched exefs, why not use one of the existing alternatives like [Skyline](https://github.com/skyline-dev/skyline) (compatible with Ryujinx and soon with Yuzu) or [Starlight](https://github.com/shadowninja108/Starlight) (generates a IPS patch with an extra subsdk file that contains the code)? I have no intention to call you out on that, but I'm not sure distributing an edited copyrighted executable is a good idea if you want to protect yourselves from takedown notices.

Hello thanks for this, The instructions gave me a heart attack as well and when I tried to install in tinfoil I kept getting an error for unsigned code and it wouldn’t download. Do you have copy of the files I could use to play it patch on my switch without the NSP? I’d be so grateful

**Comment by popdude731** [comment]
> Greetings,
> 
> As a fellow Switch modder, I couldn't help but notice that you seem to only distribute your patch as a NSP, which, on top of being rare, can lead to bans on hardware and is not recommended by SciresM (Atmosphere lead dev),
> 
> After some manipulations, I compared what files you guys have edited to the base game and used them through layeredFS on Switch, and it worked flawlessly for a full run of Arcueid's route (massive props to the translation team btw, amazing work and no typo).
> 
> Why did I bother to do this? Well, as I said, NSPs are unsafe on Switch and I think you guys would benefit a lot from distributing the patch for use with LayeredFS for the safety of your users (on top of not giving them a heart attack when reading the instructions).
> 
> I'm aware the installation guide mentions you will not take responsibility for bans, and that's totally fair, but you wouldn't need to warn people if you distributed a safe alternative. And hey, you can still keep the NSP way for ease of use on emulators!
> 
> I also noticed you distribute a patched exefs, why not use one of the existing alternatives like [Skyline](https://github.com/skyline-dev/skyline) (compatible with Ryujinx and soon with Yuzu) or [Starlight](https://github.com/shadowninja108/Starlight) (generates a IPS patch with an extra subsdk file that contains the code)? I have no intention to call you out on that, but I'm not sure distributing an edited copyrighted executable is a good idea if you want to protect yourselves from takedown notices.

Heyya!
Was wondering if you still had the files to play this as a mod, as opposed to a NSP?
I wanna play this so bad, but I'm not sure how to do it with a legal copy of the game without using Skyline or something like that.

**Comment by rschlaikjer** [comment]
As part of our final release, we have included a script and instructions for converting the NSP patch to a layeredfs patch. 
You can find them on the website here.
https://tsukihimates.com/patch/#atmosphere_layeredfs
